[workspace]
project = "remorseless-records"

[[services]]
name = "next-storefront"
root = "./storefront"

environment = { NODE_ENV = "production" }
setup = { nixPkgs = ["nodejs_22", "pnpm_10"] }
install = { cmd = "pnpm install --frozen-lockfile" }
build = { cmd = "pnpm run build" }
start = { cmd = "pnpm run start" }
