packages:
  - "."

allowBuilds:
  "@medusajs/telemetry": true
  "@swc/core": true
  esbuild: true
  lefthook: true
  msgpackr-extract: true
  protobufjs: true
  puppeteer: true
  sharp: true

overrides:
  "@mikro-orm/cli": 6.6.14
  "@mikro-orm/core": 6.6.14
  "@mikro-orm/knex": 6.6.14
  "@mikro-orm/migrations": 6.6.14
  "@mikro-orm/postgresql": 6.6.14
  "@opentelemetry/exporter-prometheus": 0.217.0
  "@opentelemetry/sdk-node": 0.217.0
  "@isaacs/brace-expansion": ^5.0.1
  "@remix-run/router": ^1.23.2
  "ajv@>=7.0.0 <8.18.0": ^8.20.0
  axios: ^1.15.2
  brace-expansion: ^2.0.3
  devalue: ^5.8.1
  diff: ^4.0.4
  esbuild: ^0.25.12
  fast-xml-parser: ^5.8.0
  follow-redirects: ^1.16.0
  flatted: ^3.4.2
  i18next-http-backend: ^3.0.5
  immutable: ^3.8.3
  js-cookie: ^3.0.7
  "js-yaml@<=4.1.1": ^4.2.0
  jws: 3.2.3
  lodash: ^4.18.1
  "minimatch@<3.1.4": ^3.1.4
  "minimatch@>=9.0.0 <9.0.7": ^9.0.7
  "minimatch@>=10.0.0 <10.2.3": ^10.2.5
  multer: ^2.2.0
  "path-to-regexp@<0.1.13": 0.1.13
  "path-to-regexp@>=8.0.0 <8.4.0": ^8.4.2
  "picomatch@<2.3.2": ^2.3.2
  "picomatch@>=4.0.0 <4.0.4": ^4.0.4
  postcss: ^8.5.15
  protobufjs: ^7.6.3
  qs: ^6.15.2
  react-router: ^6.30.4
  react-router-dom: ^6.30.4
  rollup: ^4.60.4
  semver: ^7.5.2
  "undici@>=7.0.0 <7.28.0": ^7.28.0
  uuid: ^11.1.1
  "vite@<=6.4.2": ^6.4.3
  "vite@>=7.0.0 <=7.3.1": ^7.3.2
  "form-data@>=4.0.0 <4.0.6": ^4.0.6
  "ws@>=7.0.0 <7.5.11": ^7.5.11
  "@opentelemetry/core": ^2.8.0
